# Generated by Django 3.1.4 on 2020-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=150)),
                ('release_date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
